cart/urls.py
from django.urls import path
from cart.views import (CartView,cart_add,cart_update,cart_delete)

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='list'),
    path('add/', cart_add, name='create'),
    path('update/', cart_update, name='update'),
    path('delete/', cart_delete, name='delete'),
]

shopping/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('',include('store.urls',namespace='store')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('dashboard/article/',include('articles.urls',namespace='article')),
    path('dashboard/customer/',include('customers.urls',namespace='customer')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import (HomeView, CatalogView, ArticleDetailView, RegisterView,LoginView,DashboardView)

app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('catalog/',CatalogView.as_view(), name='catalog'),
    path('catalog/<slug:slug>/',CatalogView.as_view(), name='catalog_detail'),
    path('articles/<slug:slug>/',ArticleDetailView.as_view(), name='article_detail'),
    path('register/',RegisterView.as_view(), name='register'),
    path('login/',LoginView.as_view(), name='login'),
    path('dashboard/',DashboardView.as_view(), name='dashboard'),
]

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.contrib.gis.geometry import json_regex
from django.views.generic import TemplateView
from django.shortcuts import get_object_or_404
from django.http import JsonResponse
from articles.models import Article
from cart.cart import Cart

# cart page view content
class CartView(TemplateView):
    template_name = 'cart/cart_main.html'

    def get_context_data(self, **kwargs):
        cart = Cart(self.request)
        context = super().get_context_data(**kwargs)
        context['cart_articles'] = cart
        context['cart_total'] = cart.get_total()
        return context



def cart_add(request):
    context = {}
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        article_id = int(request.POST.get('article_id'))
        article_qty = int(request.POST.get('article_qty',1))
        article_override = bool(request.POST.get('article_override',False))
        art = get_object_or_404(Article, id=article_id)
        cart.add(article=art, quantity=article_qty, override=article_override)
        cart_quantity = len(cart)
        context['quantity'] = cart_quantity
        context['message'] = f"L'article {art.name} a bien été rajouter dans le panier"

        return JsonResponse(context)
    context['message'] = 'Non valid'
    return JsonResponse(context)
def cart_update(request):
    context = {}
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        article_id = int(request.POST.get('article_id'))
        article_qty = int(request.POST.get('article_qty', 1))
        art = get_object_or_404(Article, id=article_id)
        cart.update(article=art, quantity=article_qty)
        context['message'] = f"L'article {art.name} a bien été rajouter dans le panier"
        return JsonResponse(context)
    context['message'] = 'Non valid'
    return JsonResponse(context)



def cart_delete(request):
    context = {}
    cart = Cart(request)
    if request.POST.get('action') == 'post':
        article_id = int(request.POST.get('article_id'))
        art = get_object_or_404(Article, id=article_id)
        cart.remove(article=art)
        context['message'] = f"L'article {art.name} a bien été retirer dans le panier"
        return JsonResponse(context)
    context['message'] = 'Non valid'
    return JsonResponse(context)

cart/templates/cart/cart_main.html
{# templates/cart/main.html #}
{% extends 'front/base.html' %}
{% block title %}Panier{% endblock title %}
{% load price_form %}
{% load static %}
{% block content %}
    <section class="subheader-section"><!-- Start breadcrumb-->
        <div class="head d-flex flex-wrap">
            <a href="{% url 'store:home' %}">
                Accueil
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <a href="{% url 'store:catalog' %}">
                Catalogue
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <span>Panier</span>
        </div>
    </section><!-- End breadcrumb-->
    <section class="cart-section">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 col-xl-7 mb-5 ms-auto me-auto"><!--ms-auto me-auto-->
                    <div class="cart-left-content">
                        <div class="cart-table">
                            <table class="cart-table-item">
                                <tr class="table-head">
                                    <th class="column-1">Article</th>
                                    <th class="column-2"></th>
                                    <th class="column-3">Prix</th>
                                    <th class="column-4">Quantité</th>
                                    <th class="column-5">Total</th>
                                </tr>
                                {% for item in cart_articles %}
                                    <tr class="table-item">
                                        <td class="column-1">
                                            <div class="cart-image" data-filter="{{ item.article.pk }}">
                                                <img src="{{ item.article.thumbnail.url }}" alt="IMG Product">
                                            </div>
                                        </td>
                                        <td class="column-2">
                                            <span class="cart-name">{{ item.article.name }}</span>
                                            <span class="cart-category">{{ item.article.category.name }}</span>
                                        </td>
                                        <td class="column-3">{{ item.article.price | price_form }} XAF</td>
                                        <td class="column-4">
                                        <div class="cart-num d-flex flex-wrap me-0 ms-auto">
                                            <label for="cart_item_num" data-filter="{{ item.article.pk }}" class="cart-btn-down cart-qte d-flex justify-content-center align-items-center">
                                                <i class="fa-solid fa-minus"></i>
                                            </label>
                                            <input type="number" value="{{ item.quantity }}" min="1" max="{{ item.article.stock }}"  name="cart_item_num" id="cart_item_num" class="cart-qte-num text-center" />
                                            <label for="cart_item_num" data-filter="{{ item.article.pk }}" class="cart-btn-up cart-qte d-flex justify-content-center align-items-center">
                                                <i class="fa-solid fa-plus"></i>
                                            </label>
                                        </div>
                                    </td>
                                        <td class="column-5">{{ item.total_price|price_form }} XAF</td>
                                    </tr>
                                {% empty %}
                                    <tr>
                                        <td colspan="5" class="text-center text-muted py-3">

                                            Aucun article dans le panier
                                        </td>
                                    </tr>
                                {% endfor %}

                            </table>
                        </div>
                        <div class="cart-promo d-flex flex-wrap justify-content-between align-items-center">
                            <div class="cart-coupon d-flex flex-wrap align-items-center">
                                <input type="text" name="" id="" placeholder="Entrez votre coupon">
                                <div class="cart-coupon-text d-flex justify-content-center align-items-center">
                                    Code promo
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-sm-10 col-lg-7 col-xl-5 mb-5 ms-auto me-auto">
                    <div class="cart-right-content">
                        <h4>Total panier</h4>
                        <div class="cart-sum-prod d-flex flex-wrap align-items-start">
                            <div class="cart-label">
                                <span>Total : </span>
                            </div>
                            <div class="cart-current-price">
                                <span>{{ cart_total | price_form}} XAF</span>
                            </div>
                        </div>
                        <div class="cart-prod-detail d-flex flex-wrap align-items-start">
                            <div class="cart-prod-label">
                                <span>Vente : </span>
                            </div>
                            <div class="cart-prod-text">
                                <p>There are no shipping methods available. Please double check your address, or contact us if you need any help.</p>
                            </div>
                        </div>
                        <div class="group-form py-4">
                            <input type="text" name="" id="" placeholder="Entrez votre nom" class="form-control mb-2">
                            <input type="text" name="" id="" placeholder="Entrez votre numéro" class="form-control mb-2">
                            <select name="city"  class="form-control">
                                <option value="None" disabled selected>Veuillez entrer la ville</option>
                                <option value="BZV">Brazzaville</option>
                                <option value="PN">Pointe-Noire</option>
                            </select>
                        </div>
                        <div class="cart-prod-price d-flex flex-wrap align-items-start">
                            <div class="cart-price-label">
                                <span>Total</span>
                            </div>
                            <div class="cart-price-value">
                                <span>$79.65</span>
                            </div>
                        </div>
                        <button class="btn btn-primary w-100">Valider</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'cart/index.js' %}"></script>
{% endblock scripts %}