cart/urls.py
from django.urls import path
from cart.views import (CartView,cart_add,cart_update,cart_delete)

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='list'),
    path('add/', cart_add, name='create'),
    path('update/', cart_update, name='update'),
    path('delete/', cart_delete, name='delete'),
]

shopping/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('',include('store.urls',namespace='store')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('dashboard/article/',include('articles.urls',namespace='article')),
    path('dashboard/customer/',include('customers.urls',namespace='customer')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/urls.py
from django.urls import path
from store.views import (HomeView, CatalogView, ArticleDetailView, RegisterView,LoginView,DashboardView)

app_name = 'store'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('catalog/',CatalogView.as_view(), name='catalog'),
    path('catalog/<slug:slug>/',CatalogView.as_view(), name='catalog_detail'),
    path('articles/<slug:slug>/',ArticleDetailView.as_view(), name='article_detail'),
    path('register/',RegisterView.as_view(), name='register'),
    path('login/',LoginView.as_view(), name='login'),
    path('dashboard/',DashboardView.as_view(), name='dashboard'),
]

store/views.py
from django.views.generic import TemplateView, ListView, DetailView, CreateView,FormView
from django.shortcuts import redirect,render
from django.core.paginator import EmptyPage,PageNotAnInteger
from django.contrib import messages
from users.forms import RegisterShopperUser,LoginFormUser
from users.models import Shopper
from articles.models import Article, Category
from shopping.utils import send_email
from django.contrib.auth import authenticate, login, logout



# Home page view content
class HomeView(TemplateView):
    template_name = 'store/main.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['articles'] = Article.objects.all().order_by('-created')[:4]
        context['categories'] = Category.objects.all()
        return context

# catalog page view content
class CatalogView(ListView):
    model = Article
    template_name = "store/main_catalog.html"
    paginate_by = 12

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            try:
                category = Category.objects.get(slug=slug)
            except Category.DoesNotExist:
                return redirect('store:catalog')
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_name'] = self.kwargs.get('slug')
        return context

    def get_queryset(self):
        slug = self.kwargs.get('slug')

        if slug:
            return super().get_queryset().filter(category__slug=slug)[::-1]
        return super().get_queryset()[::-1]


    def pagination(self,queryset,page_size):

        paginator = self.get_paginator(queryset, page_size)
        page = self.request.GET.get('page')
        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        return (paginator,page_obj,page_obj.object_list,page_obj.has_other_pages())
# article detail page view content
class ArticleDetailView(DetailView):
    model = Article
    template_name = 'store/main_article.html'
    object = 'article'

# Register shopper view content
class RegisterView(CreateView):
    model = Shopper
    form_class = RegisterShopperUser
    template_name = 'store/main_register.html'

    def post(self, request, *args, **kwargs):
        context = { }
        post_data = request.POST.copy()
        if not post_data['password1'] or post_data['password1'] != post_data['password']:
            form = RegisterShopperUser(post_data)
            messages.warning(request, 'Le mot de passe est incorrect.')
            context['form'] = form
            return render(request, self.template_name, context)


        post_data['username'] = post_data['username'].replace(' ', '_').title()
        form = RegisterShopperUser(post_data)

        if form.is_valid():
            shopper = form.save()
            messages.success(request, f"Compte de {shopper.username} a été  créé avec succès !")

            """ Sending Email
            subject = "Bienvenue sur mercibil"
            receivers = ["localhost"]
            template_email = "customers/customer_email.html"
            context_email = {
                'username': post_data['username'].replace('_', ' ').title(),
                'email': post_data['email'],
            }
            send_email(subject, receivers, template_email, context_email)
             end email"""
            return redirect('store:login')
        messages.error(request, 'Le compte n\'a pas pu être créer !')
        context["form"] = form
        return render(request, self.template_name, context)
# Login page view content
class LoginView(FormView):
    form_class = LoginFormUser
    template_name = 'store/main_login.html'
    def post(self, request, *args, **kwargs):
        context = { }
        form = LoginFormUser(request.POST)
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, email=email, password=password)

        if user is not None:
            login(request, user)
            return redirect('store:dashboard')
        messages.warning(request,'Votre email ou mot de passe est incorrect !')
        context["form"] = form

        return render(request, self.template_name, context)



class DashboardView(TemplateView):
    template_name = 'store/main_dashboard.html'

store/templates/store/main_article.html
{# templates/store/main_article.html #}
{% extends 'front/base.html' %}
{% load static %}
{% load price_form %}
{% block title %}{{ article.name }}{% endblock title %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/libraries/swiper-bundle.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/libraries/magnific-popup.css' %}" />
{% endblock style %}

{% block content %}
    <section class="subheader-section"><!-- Start breadcrumb-->
        <div class="head d-flex flex-wrap">
            <a href="{% url 'store:home' %}">
                Accueil
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <a href="{% url 'store:catalog' %}">
                Catalogue
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <a href="{{ article.category.get_absolute_url }}">
                {{ article.category.name }}
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <span>{{ article.name }}</span>
        </div>
    </section><!-- End breadcrumb-->
    <section class="article-detail-section">
        <div class="container">
            <div class="row">
                <div class="col-md-6 col-lg-7"><!-- Start product detail images -->
                    <div class="article-detail-image d-flex justify-content-between align-items-start">
                    <div class="sw-article detail-article"><!-- Start product description images -->

                        <div class="swiper-wrapper">
                            {% for detail in article.article_images %}
                            <div class="swiper-slide">
                                <img src="{{ detail.image.url }}" alt="IMG ARTICLE">
                                <div class="overlay-article"></div>
                            </div>
                            {% endfor %}

                        </div>
                    </div><!-- End product description images -->
                    <div class="sw-article detail-slide">
                        <div class="swiper-wrapper">
                            {% for img in article.article_images %}
                            <div class="swiper-slide">
                                <div class="detail d-block">
                                    <img src="{{ img.image.url }}" alt="IMG ARTICLE">
                                    <a href="{{ img.image.url }}" class="article-expand d-flex justify-content-center align-items-center">
                                        <i class="fa-solid fa-expand"></i>
                                    </a>
                                </div>
                            </div>
                            {% endfor %}
                        </div>
                        <div class="sw-arrows d-flex justify-content-between"><!-- Start button article details-->
                            <button type="button" class="sw-nav-btn sw-prev">
                                <i class="fa-solid fa-chevron-left"></i>
                            </button>
                            <button type="button" class="sw-nav-btn sw-next">
                                <i class="fa-solid fa-chevron-right"></i>
                            </button>
                        </div><!-- End button article details-->
                    </div>
                </div>
                </div><!-- End product detail images -->
                <div class="col-md-6 col-lg-5">
                <div class="article-detail-description">
                    <h3>
                        {{ article.name }}
                        <span>Catégorie : {{ article.category.name }}</span>
                    </h3>
                    <div class="rating rating-5">
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                        <i class="fa-solid fa-star"></i>
                    </div>
                    <div class="article-desc-price">
                        {{ article.price | price_form }} XAF
                    </div>
                    <p>{{ article.description|truncatechars:140 }}</p>
                    <form class="article-btn">
                        {% csrf_token %}
                        <div class="article-qty">
                            <span>Quantité :</span>
                            <div class="art-num d-flex flex-nowrap">
                                <label for="cart_num" class="btn-num-down qty-num d-flex justify-content-center align-items-center">
                                    <i class="fa-solid fa-minus"></i>
                                </label>
                                <input type="text" name="cart_num" id="cart_num" value="1"  class="qty-value" />
                                <label for="cart_num" class="btn-num-up qty-num d-flex justify-content-center align-items-center">
                                    <i class="fa-solid fa-plus"></i>
                                </label>
                            </div>
                        </div>
                        <button type="submit" id="add_cart" value="{{ article.pk }}" class="art-cart-add d-flex justify-content-center align-items-center">
                            <i class="fa-solid fa-shopping-bag"></i>
                            Ajouter
                        </button>
                    </form>
                    <div class="art-detail-widget">
                        <ul>
                            <li>
                                <span>Label :</span>
                                <p>Nouveau</p>
                            </li>
                            <li>
                                <span>Disponibilité :</span>
                                {% if article.stock %}
                                <div class="stock-checkbox">
                                    <label for="stockIn">
                                        état de stock
                                        <input type="checkbox" id="stockIn" disabled checked />
                                        <span class="checkmark"></span>
                                    </label>
                                </div>
                                {% else %}
                                    <p>En rupture</p>
                                {% endif %}
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'js/libraries/swiper-bundle.min.js' %}"></script>
    <script src="{% static 'js/libraries/jquery.magnific-popup.min.js' %}"></script>
    <script src="{% static 'store/article.js' %}"></script>
{% endblock scripts %}

store/templates/store/main_catalog.html
{# templates/store/main_catalog.html #}
{% extends 'front/base.html' %}
{% load price_form %}
{% block title %}Catalogue{% endblock title %}

{% block content %}
    <section class="subheader-section"><!-- Start breadcrumb-->
        {% if category_name %}
            <div class="head d-flex flex-wrap">
                <a href="{% url 'store:home' %}">
                    Accueil
                    <i class="fa-solid fa-chevron-right"></i>
                </a>
                <a href="{% url 'store:catalog' %}">
                    Catalogue
                    <i class="fa-solid fa-chevron-right"></i>
                </a>
                <span>{{ category_name }}</span>
            </div>
        {% else %}
            <div class="head d-flex flex-wrap">
                <a href="{% url 'store:home' %}">
                    Accueil
                    <i class="fa-solid fa-chevron-right"></i>
                </a>
                <span>Catalogue</span>
            </div>
        {% endif %}
    </section><!-- End breadcrumb-->
    <section class="article-section"><!-- start article section-->
        <div class="container">
            <div class="row">
                {% for article in object_list %}
                    <div class="col-sm-6 col-md-4 col-lg-3 mb-4"><!-- Start product item-->
                        <article class="article-item border rounded p-2">
                            <div class="article-up">
                                <img src="{{ article.thumbnail.url}}" alt="IMG-PRODUCT">
                                <ul class="article-hover"><!--Start hover button -->
                                    <li><a href="#"><i class="fa-solid fa-expand"></i></a></li>
                                    <li><a href="#"><i class="fa-solid fa-bag-shopping"></i></a></li>
                                    <li>
                                        <a href="#"  class="addCart" data-article="{{ article.id }}" role="button">
                                            <i class="fa-solid fa-plus"></i>
                                        </a>
                                    </li>
                                </ul><!--End hover button -->
                            </div>
                            <div class="article-down">
                                <div class="d-flex align-items-start justify-content-between flex-wrap flex-column">
                                    <a href="{{ article.get_absolute_url }}" class="article-name">{{ article.name }}</a>
                                    <div class="rating rating-4">
                                        <i class="fa-solid fa-star"></i>
                                        <i class="fa-solid fa-star"></i>
                                        <i class="fa-solid fa-star"></i>
                                        <i class="fa-solid fa-star"></i>
                                        <i class="fa-solid fa-star"></i>
                                    </div>
                                </div>
                            </div>
                            <div class="article-detail"><!--Start product detail-->
                                <span class="article-price">{{ article.price | price_form }} XAF</span>
                            </div>
                        </article>
                    </div><!-- End product item -->
                {% empty %}
                    <div class="text-center text-muted">Aucun article trouvé</div>
                {% endfor %}
                {% if object_list %}
                <div class="col-12">
                    <div class="pagination-articles">
                        <ul class="article-pagination">
                            {% if page_obj.has_previous %}
                            <li>
                                <a href="?page={{ page_obj.previous_page_number }}">
                                    <i class="fa-solid fa-chevron-left"></i>
                                </a>
                            </li>
                            {% endif %}
                            {% for num in page_obj.paginator.page_range  %}
                                {% if page_obj.number == num %}
                                    <li class="active">
                                        <span>{{ num }}</span>
                                    </li>
                                {% else %}
                                    <li><a href="?page={{ num }}">{{ num }}</a></li>
                                {% endif %}
                            {% endfor %}
                             {% if page_obj.has_next %}
                                <li>
                                <a href="?page={{ page_obj.next_page_number }}">
                                    <i class="fa-solid fa-chevron-right"></i>
                                </a>
                            </li>
                            {% endif %}
                        </ul>
                    </div>
                </div>
                {% endif %}
            </div>
        </div>
    </section>
{% endblock content %}

store/templates/store/main_dashboard.html
{# templates/store/main_dashboard.html #}
{% extends 'back/base.html' %}

store/templates/store/main_login.html
{# templates/store/main_login.html #}
{% extends 'front/base.html' %}
{% load form_field %}
{% block title %}Connexion{% endblock title %}

{% block content %}
    <section class="login-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="section-heading text-center mb-5">
                        <h2>Connexion</h2>
                        <span>Connectez vous à votre compte en toute sécurité</span>
                    </div>
                    {% include 'front/static/flash_message.html' %}
                    <form  method="post">
                        {% csrf_token %}
                        <div class="row">
                            {% for field in form %}
                                <div class="col-12 mb-3">
                                    {% if field.errors %}
                                        {{ field | add_class:'form-control is-invalid' }}
                                        <div class="invalid-feedback">
                                            {{ field.errors }}
                                        </div>
                                    {% else %}
                                        {{ field }}
                                    {% endif %}
                                </div>
                            {% endfor %}
                            <div class="col-12 main-border-button">
                                <button type="submit" class="w-100">Connexion</button>
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-12 ps-0 mt-4">
                            Si vous ne possédez pas compter.
                            <a href="{% url 'store:register' %}" class="text-primary">Créer un nouveau compte</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}

store/templates/store/main_register.html
{# templates/store/main_register.html #}
{% extends 'front/base.html' %}
{% load form_field %}
{% block title %}Création{% endblock title %}
{% block content %}
    <section class="subheader-section"><!-- Start breadcrumb-->
        <div class="head d-flex flex-wrap">
            <a href="{% url 'store:home' %}">
                Accueil
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <a href="{% url 'store:catalog' %}">
                Catalogue
                <i class="fa-solid fa-chevron-right"></i>
            </a>
            <span>Création de compte</span>
        </div>
    </section><!-- End breadcrumb-->
    <section class="register-section">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="section-heading text-center mb-5">
                        <h2>Création d'un compte</h2>
                        <span>Créer un nouveau compte utilisateur</span>
                    </div>
                    {% include 'front/static/flash_message.html' %}
                    <form  method="post">
                        {% csrf_token %}
                        <div class="row">
                            {% for field in form %}
                                {% if field.name != 'usable_password' %}
                                    <div class="col-12 mb-3">
                                        {% if field.errors %}
                                            {{ field | add_class:'form-control is-invalid' }}
                                            <div class="invalid-feedback">
                                                 {{ field.errors }}
                                            </div>
                                        {% else %}
                                            {{ field }}
                                        {% endif %}
                                    </div>
                                {% endif %}
                            {% endfor %}
                            <div class="col-12 mb-3 main-border-button">
                                <button type="submit" class="w-100">Créer</button>
                            </div>
                        </div>
                    </form>
                    <div class="row">
                        <div class="col-12 ps-0 mt-4">
                            Vous possédez déjà un compte.
                            <a href="{% url 'store:login' %}" class="text-primary">Connectez-vous à votre compte</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}