articles/urls.py
from django.urls import path
from articles.views import (ArticleListView,ArticleCreateView,ArticleUpdateView,CategoryListView,category_delete)


app_name = 'articles'


urlpatterns = [
    path('',ArticleListView.as_view(),name='list'),
    #path('<str:slug>/',ArticleListView.as_view(),name='category_detail'),
    path('new/',ArticleCreateView.as_view(),name='new'),
    path('<str:slug>/edit/',ArticleUpdateView.as_view(),name='edit'),
    path('category/', CategoryListView.as_view(), name='category_list'),
    path('category/delete/',category_delete,name='category_delete'),
]

cart/urls.py
from django.urls import path
from cart.views import (CartView,cart_add,cart_update,cart_delete)

app_name = 'cart'

urlpatterns = [
    path('', CartView.as_view(), name='list'),
    path('add/', cart_add, name='create'),
    path('update/', cart_update, name='update'),
    path('delete/', cart_delete, name='delete'),
]

shopping/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path,include
from django.conf.urls.static import static

urlpatterns = [
    path('',include('store.urls',namespace='store')),
    path('cart/',include('cart.urls',namespace='cart')),
    path('dashboard/article/',include('articles.urls',namespace='article')),
    path('dashboard/customer/',include('customers.urls',namespace='customer')),
    path('admin/', admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articles/models.py
from django.db import models
from django.utils.text import slugify
from django.shortcuts import reverse
from articles.utils import generate_slug



class Category(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100, unique=True,blank=True)
    image = models.ImageField(upload_to='categories/',default='default_category.jpg')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def articles(self):
        return Article.objects.filter(category=self)

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        return reverse('store:catalog_detail',kwargs={'slug':self.slug})

   # def get_detail_url(self):
    #    return reverse('article:category_detail',kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class Article(models.Model):
    name = models.CharField(max_length=100)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(max_length=8, unique=True,blank=True)
    description = models.TextField(blank=True,null=True)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    genre = models.CharField(max_length=20,default='woman')
    label = models.CharField(max_length=15,default='without')
    stock = models.PositiveIntegerField(default=0)
    thumbnail = models.ImageField(upload_to='articles_portail/',blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    @property
    def article_images(self):
        return ArticleImage.objects.filter(article=self)



    def __str__(self):
        return f"{self.name}-({self.stock})"

    def get_absolute_url(self):
        return reverse('store:article_detail',kwargs={'slug':self.slug})

    def get_detail_url(self):
        return reverse('article:edit',kwargs={'slug':self.slug})

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = generate_slug()
        return super().save(*args, **kwargs)

class ArticleImage(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE,null=True,blank=True,related_name='images')
    image = models.ImageField(upload_to='articles_images/')

    def __str__(self):
        return f"{self.article.name}"

articles/forms.py
from django import forms
from articles.models import Category,Article,ArticleImage

GENRE_CHOICES = [
    ('woman','Femme'),
    ('man','Homme'),
    ('kid','Enfant'),
    ('mixed','Mixte')
]

LABEL_CHOICES = [
    ('new','Nouveau'),
    ('sale','Solde'),
    ('without','Sans')
]
class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['name','image']

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ['name','category','genre','price','stock','label','thumbnail','description']
        widgets = {
            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Article...'}),
            'category': forms.Select(attrs={'class':'form-control','placeholder':'Type d\'article...'}),
            'price': forms.NumberInput(attrs={'class':'form-control','placeholder':'Prix de l\'article...'}),
            'stock': forms.NumberInput(attrs={'class':'form-control','placeholder':'Nombre d\'articles'}),
            'genre': forms.Select(choices=GENRE_CHOICES,attrs={'class':'form-control','placeholder':'Sélectionner un genre'}),
            'label': forms.Select(choices=LABEL_CHOICES,attrs={'class':'form-control','placeholder':'Choisissez un label '}),
            'thumbnail': forms.ClearableFileInput(attrs={'class':'form-control','placeholder':'Sélectionnez une image de l\'article'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description...'}),
        }
        labels = {
            'name': "Nom de l'article",
            'category': "Catégorie",
            'price': "Prix de l'article",
            'stock': "Stock",
            'genre': "Style",
            'label': "Etiquette",
            'thumbnail': 'Image principale',
            'description': "Description de l'article",


        }

    def __init__(self, *args, **kwargs):
        super(ArticleForm, self).__init__(*args, **kwargs)
        self.fields['category'].queryset = Category.objects.all().order_by('name')

class ArticleImageForm(forms.ModelForm):
    class Meta:
        model = ArticleImage
        fields = ['image']

articles/views.py
from django.core.paginator import PageNotAnInteger, EmptyPage
from django.contrib import messages
from django.http import JsonResponse
from django.views.generic import ListView, UpdateView,CreateView
from django.shortcuts import render, redirect
from articles.models import Article,Category,ArticleImage
from articles.forms import CategoryForm,ArticleForm


# Article list view content
class ArticleListView(ListView):
    model = Article
    template_name = 'articles/article_main.html'
    context_object_name = 'articles'
    paginate_by = 5
    ordering = ['-created']

    def get(self, request, *args, **kwargs):
        slug = self.kwargs.get('slug')
        if slug:
            try:
                articles = Category.objects.get(slug=slug)
            except Category.DoesNotExist:
                return redirect('article:list')
        return super().get(request, *args, **kwargs)
    def get_queryset(self):
        slug = self.kwargs.get('slug')
        if slug:
            return super().get_queryset().filter(category__slug=slug)
        return super().get_queryset()

    def paginate_queryset(self, queryset, page_size):
        paginator = self.get_paginator(queryset, page_size)
        page = self.request.GET.get('page')

        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        return (paginator,page_obj,page_obj.object_list,page_obj.has_other_pages())

    def post(self, request, *args, **kwargs):
        context = {
            'status':''
        }
        art_id = request.POST.get('id')
        try:
            article = Article.objects.get(id=art_id)
            article.delete()
            messages.success(request, f'Article {article.name} a été supprimer avec succès !')
            context['status'] = True
            return JsonResponse(context)
        except Article.DoesNotExist:
            messages.error(request, "Cet article n'existe pas dans notre catalogue !")
        except:
            messages.error(request, 'La suppression a échouée !')
        context['status'] = False
        return JsonResponse(context)

# Article create view content
class ArticleCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articles/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pageTitle'] = 'Créer un nouvel article'
        return context

    def post(self, request, *args, **kwargs):
        context = {
            'pageTitle': 'Créer un nouvel article'
        }
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save()
            if request.FILES.get('images'):
                for image in request.FILES.getlist('images'):
                    ArticleImage.objects.create(article=article,image=image)

            messages.success(request, f"L'article {article.name} a été ajouté avec succès !")
            return redirect('articles:list')
        else:
            messages.warning(request, "La création d'un nouvel article a échoué ..!")
        context['form'] = form
        return render(request,'articles/article_detail.html',context)

# Article update view content
class ArticleUpdateView(UpdateView):
    model = Article
    form_class = ArticleForm
    template_name = 'articles/article_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['pageTitle']= 'Modification de l\'article'
        context['images'] = ArticleImage.objects.filter(article=self.get_object())
        return context

    def post(self, request, *args, **kwargs):
        context = {
            'pageTitle': 'Modification de l\'article'
        }
        article = self.get_object()
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()

            if request.FILES.get('images'):
                for image in request.FILES.getlist('images'):
                    ArticleImage.objects.update_or_create(article=article,image=image)
            messages.success(request,"La mise de l'article "+article.name+" a été mis à jour ...!")
            return redirect('articles:list')
        else:
            context['form'] = form
            context['images'] = ArticleImage.objects.filter(article=article)
        messages.error(request,'La modification a échouée. Veuillez réessayer !')
        return render(request,'articles/article_detail.html',context)




# Category list view content
class CategoryListView(ListView):
    model = Category
    template_name = 'articles/category_main.html'
    paginate_by = 4
    ordering = ['name']

    def paginate_queryset(self, queryset, page_size):
        paginator = self.get_paginator(queryset, page_size)
        page = self.request.GET.get('page')

        try:
            page_obj = paginator.page(page)
        except PageNotAnInteger:
            page_obj = paginator.page(1)
        except EmptyPage:
            page_obj = paginator.page(paginator.num_pages)

        return (paginator,page_obj,page_obj.object_list,page_obj.has_other_pages())

    def post(self, request, *args, **kwargs):
        context = { }

        category_id = request.POST.get('id') if request.POST.get('id') else None

        if category_id != 'undefined' and category_id:
            try:
                category = Category.objects.get(id=category_id)

            except Category.DoesNotExist:
                context['status'] = 'danger'
                context['message'] = 'Cette action ne peut être exécuter !'
                return JsonResponse(context,status=400)


        else:
            category = None
        form = CategoryForm(request.POST, request.FILES,instance=category)

        if form.is_valid():
            form.save()
            msg = 'Nouvelle catégorie ajoutée avec succès !' if category_id =='undefined' else 'La catégorie a bien été modifier avec succès !'
            messages.success(request, msg)
            context['status'] = 'success'
            return JsonResponse(context,status=200)
        else:
            context['errors'] = form.errors.as_json()
            context['status'] = 'warning'
            context['message'] = 'Les informations entrées ne sont pas acceptables !'

        return JsonResponse(context,status=400)

# category delete view content
def category_delete(request):
    context= {}
    if request.method == 'POST':
        category_id = request.POST.get('id')
        try:
            category = Category.objects.get(id=category_id)
            category.delete()
            messages.success(request,'La suppression a bien été exécuté !')
            context['status'] = True
        except Category.DoesNotExist:
            messages.error(request,"Cette catégorie n'existe pas !")
        except:
            messages.error(request,'La suppression a échouée !')
    context['status'] = False

    return JsonResponse(context)

articles/templates/articles/article_detail.html
{# templates/articles/article_detail.html #}
{% extends 'back/base.html' %}
{% load static %}
{% load form_field %}
{% block title %}Article{% endblock title %}
{% block style %}
    <link rel="stylesheet" href="{% static 'css/libraries/dropzone.css' %}">
{% endblock style %}
{% block content %}
    <section class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-2 align-items-center">
                <div class="col"><!-- Start Page pre-title -->
                    <div class="page-pretitle">
                        Article
                    </div>
                    <h2 class="page-title">
                        {{ pageTitle }}
                    </h2>
                </div><!-- End Page pre-title -->
            </div>
        </div>
    </section>
    <section class="page-body">
        <div class="container-xl">
            <div class="row justify-content-center">
                <div class="col-12 col-md-8">
                    {% include 'back/static/flash_message.html' %}
                    <div class="card">
                        <form id="art-form" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <div class="row py-4">
                                {% for field in form %}
                                    {% if field.id_for_label == 'id_category' or field.id_for_label == 'id_genre' %}
                                        <div class="col-md-6 mb-2 px-4">
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="form-label required">{{ field.label }}</label>
                                                {% if field.errors %}
                                                    {{ field|add_class:'form-control is-invalid' }}
                                                    <div class="invalid-feedback">
                                                        {{ field.errors }}
                                                    </div>
                                                {% else %}
                                                    {{ field }}
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% elif field.id_for_label == 'id_price' %}
                                        <div class="col-6 col-sm-7 col-lg-9 ps-4 pe-2 mb-2">
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="form-label required">{{ field.label }}</label>
                                                {% if field.errors %}
                                                    {{ field|add_class:'form-control is-invalid' }}
                                                    <div class="invalid-feedback">
                                                        {{ field.errors }}
                                                    </div>
                                                {% else %}
                                                    {{ field }}
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% elif field.id_for_label == 'id_stock' %}
                                        <div class="col-6 col-sm-5 col-lg-3 px-4 mb-2">
                                            <div class="form-group">
                                                <label for="{{ field.id_for_label }}" class="form-label required">{{ field.label }}</label>
                                                {% if field.errors %}
                                                    {{ field|add_class:'form-control is-invalid' }}
                                                    <div class="invalid-feedback">
                                                        {{ field.errors }}
                                                    </div>
                                                {% else %}
                                                    {{ field }}
                                                {% endif %}
                                            </div>
                                        </div>
                                    {% else %}
                                            <div class="col-md-12 mb-2 px-4">
                                                <div class="form-group">
                                                    <label for="{{ field.id_for_label }}" class="form-label required">{{ field.label }}</label>
                                                    {% if field.errors %}
                                                        {{ field|add_class:'form-control is-invalid' }}
                                                        <div class="invalid-feedback">
                                                        {{ field.errors }}
                                                    </div>
                                                    {% else %}
                                                        {{ field }}
                                                    {% endif %}
                                                </div>
                                            </div>
                                    {% endif %}
                                {% endfor %}
                                <div class="col-md-12 px-4 mb-4">
                                    <div class="form-group">
                                        <div class="dropzone" id="dropzone-image"></div>
                                    </div>
                                </div>
                                {% if images %}
                                    <div class="row mb-2">
                                    {% for art in images %}
                                        <div class="col-6 col-sm-4 col-md-3 col-lg-2 col-xl-1 mx-2">
                                            <img src="{{ art.image.url }}" alt="{{ art.article.name }}-image" class="img-fluid">
                                        </div>
                                    {% endfor %}
                                    </div>
                                {% endif %}
                                <div class="col-md-12 px-4">
                                    <div id="btnForm" class="btn btn-primary w-100">Valider</div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'js/libraries/dropzone-min.js' %}"></script>
    <script src="{% static 'articles/index.js' %}"></script>
{% endblock scripts %}

articles/templates/articles/article_main.html
{# templates/article/article_main.html #}
{% extends 'back/base.html' %}
{% load static %}
{% load price_form %}
{% block title %}Articles{% endblock title %}

{% block content %}
    <section class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-2 align-items-center">
                <div class="col"><!-- Start Page pre-title -->
                    <div class="page-pretitle">
                        Article
                    </div>
                    <h2 class="page-title">
                        Liste articles
                    </h2>
                </div><!-- End Page pre-title -->
                <div class="col-auto ms-auto d-print-none">
                    <div class="btn-list">
                        <a href="{% url 'article:new' %}" class="btn btn-primary d-none d-sm-inline-block" role="navigation" >
                            <i class="fa-solid fa-plus me-2"></i>
                            Nouveau
                        </a>
                        <a href="{% url 'article:new' %}"  class="btn btn-primary d-sm-none btn-icon" role="navigation" >
                            <i class="fa-solid fa-plus me-2"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="page-body">
        <div class="container-xl">
            <div class="row row-cards">
                <div class="col-12">
                    <!--  alert message -->
                    {% include 'back/static/flash_message.html' %}
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-vcenter card-table table-striped">
                                <thead>
                                    <tr>
                                        <th>Article</th>
                                        <th>Catégorie</th>
                                        <th>Prix</th>
                                        <th>Stock</th>
                                        <th>Style</th>
                                        <th>Etiquette</th>
                                        <th>Créer</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for article in articles %}
                                        <tr>
                                            <td>{{ article.name }}</td>
                                            <td>
                                                <a href="#" class="text-reset">{{ article.category.name }}</a>
                                            </td>
                                            <td class="text-secondary">{{ article.price|price_form }} XAF</td>
                                            <td class="text-secondary">{{ article.stock }}</td>
                                            <td class="text-secondary">
                                                {% if article.genre == 'woman' %}
                                                    <span class="badge bg-azure text-azure-fg">Femme</span>
                                                {% elif article.genre == 'man' %}
                                                    <span class="badge bg-cyan text-cyan-fg">Homme</span>
                                                 {% else %}
                                                    <span class="badge bg-teal text-teal-fg">Mixte</span>
                                                {% endif %}
                                            </td>
                                            <td class="text-secondary">
                                                {% if article.label == 'sale' %}
                                                    <span class="badge bg-pink-lt">En solde</span>
                                                {% elif article.label == 'new' %}
                                                    <span class="badge bg-green-lt">Nouveau</span>
                                                {% else %}
                                                    <span class="badge bg-indigo-lt">Sans</span>
                                                {% endif %}
                                            </td>
                                            <td class="text-secondary">{{ article.created|date:'d-m-Y' }}</td>
                                            <td class="icon">
                                                <div class="d-flex">
                                                    <a href="{{ article.get_detail_url }}" class="icon-link">
                                                        <i class="fa-solid fa-pen-to-square"></i>
                                                    </a>
                                                    <button type="button" class="article-item" data-filter="{{ article.name }}${{ article.pk }}" data-bs-toggle="modal" data-bs-target="#modal_popup">
                                                        <i class="fa-regular fa-trash-can"></i>
                                                    </button>
                                                </div>
                                            </td>
                                        </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer">
                            {% include 'back/static/pagination.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'js/component/widget.js' %}"></script>
    <script src="{% static 'articles/index.js' %}"></script>
{% endblock scripts %}

articles/templates/articles/category_main.html
{% extends 'back/base.html' %}
{% load static %}
{% block title %}Catégories{% endblock title %}

{% block content %}
    <section class="page-header d-print-none">
        <div class="container-xl">
            <div class="row g-2 align-items-center">
                <div class="col"><!-- Start Page pre-title -->
                    <div class="page-pretitle">
                        Article
                    </div>
                    <h2 class="page-title">
                        Catégorie d'articles
                    </h2>
                </div><!-- End Page pre-title -->
                <div class="col-auto ms-auto d-print-none">
                    <div class="btn-list">
                        <button type="button" data-filter="" class="btn btn-primary d-none d-sm-inline-block category-item"  data-bs-toggle="modal" data-bs-target="#modal_content" aria-label="Create new category">
                            <i class="fa-solid fa-plus me-2"></i>
                            Nouveau
                        </button>
                        <button type="button" class="btn btn-primary d-sm-none btn-icon category-item" data-bs-toggle="modal" data-bs-target="#modal_content" aria-label="Create new category">
                            <i class="fa-solid fa-plus me-2"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="page-body">
        <div class="container-xl">
            <div class="row row-cards">
                <div class="col-12">
                    <!--  alert message -->
                    {% include 'back/static/flash_message.html' %}
                    <div class="card">
                        <div class="table-responsive">
                            <table class="table table-vcenter card-table table-striped">
                                <thead>
                                    <tr>
                                        <th>Catégorie</th>
                                        <th>Création</th>
                                        <th>Modifier</th>
                                        <th></th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for category in object_list %}
                                    <tr>
                                        <td>
                                            <a href="#" class="text-reset">{{ category.name }}</a>
                                        </td>
                                        <td class="text-secondary" >
                                            {{ category.created | date:"d M Y" }}
                                        </td>
                                        <td class="text-secondary" >
                                            {{ category.updated | date:"d M Y" }}
                                        </td>
                                        <td class="icon">
                                            <div class="d-flex">
                                                <button type="button" class="category-item" data-filter="{{ category.name }}${{ category.pk }}" data-bs-toggle="modal" data-bs-target="#modal_content">
                                                    <i class="fa-solid fa-pen-to-square"></i>
                                                </button>
                                                <button type="button" class="category" data-filter="{{ category.name }}${{ category.pk }}" data-bs-toggle="modal" data-bs-target="#modal_popup">
                                                    <i class="fa-regular fa-trash-can"></i>
                                                </button>
                                            </div>
                                        </td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                        <div class="card-footer">
                            {% include 'back/static/pagination.html' %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock content %}
{% block scripts %}
    <script src="{% static 'js/component/widget.js' %}"></script>
    <script src="{% static 'category/index.js' %}"></script>
{% endblock scripts %}